### ISSUE TITLE
Adicionar postgresql no docker-compose.yaml

### ISSUE THREAD

**Issue by pythrick** [pythrick/drf-cookiecutter#1]
```
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
        
volumes:
  db-data: {}
```
