### ISSUE TITLE
Corrigir secrets.template.yaml

### ISSUE THREAD

**Issue by pythrick** [pythrick/drf-cookiecutter#29]
```
default:
  SECRET_KEY: GoˆgMhrCcQJmbw2o?AwrQqV53.(0{7!x
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: super_pizzaria
      USER: postgres
      PASSWORD: q2Tq9^b_q*WwrHcW
      HOST: localhost
      PORT: 5432
```

Esses valores deveriam ser placeholders
